export enum AssetPurpose {
    AVATAR = "AVATAR",
    PORTFOLIO_IMAGE = "PORTFOLIO_IMAGE",
    PORTFOLIO_COVER = "PORTFOLIO_COVER",
    VERIFICATION_DOCUMENT = "VERIFICATION_DOCUMENT",
    BOOKING_REFERENCE = "BOOKING_REFERENCE",
    CHAT_ATTACHMENT = "CHAT_ATTACHMENT",
}
